### ISSUE TITLE
build/build-solution.yml should support "version" & "versionSuffix"

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/azure-devops-templates#7]
build/build-solution.yml should support `version` & `versionSuffix` instead of only versionSuffix.

Next to that, both of them should be optional and only specified if they are specified.

Example usages:
`version` should be used similar to this:
```yaml
- task: DotNetCoreCLI@2	
  displayName: 'Compile'	
  inputs:	
    projects: 'src/*.sln'	
    arguments: '--configuration release /property:Version=${{ parameters.version}}'
```

`versionSuffix` should be used similar to this:
```yaml
- task: DotNetCoreCLI@2	
  displayName: 'Compile'	
  inputs:	
    projects: 'src/*.sln'	
    arguments: '--configuration release --version-suffix ${{ parameters.versionSuffix }}'
```
